services:
  # 1. Gateway (Nginx)
  gateway:
    build:
      context: ./services/gateway
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - api
    networks:
      - app-network
      - 
  
  #1-1. MySQL 붙이고나서 추가해줘야 함

  # 2. API Server (Spring Boot)
  api:
    build:
      context: ./services/api # 여기를 수정! (api 폴더 안을 바라보게 함)
      dockerfile: Dockerfile # 해당 폴더 안의 Dockerfile 사용
    container_name: api
    networks:
      - app-network

  # 3. Batch (Spring Batch)
  batch:
    build:
      context: ./services/batch
      dockerfile: Dockerfile
    container_name: batch
    depends_on:
      - api
    networks:
      - app-network


networks:
  app-network:
    driver: bridge