name: Spring Boot CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      # =========================
      # ✅ API
      # =========================
      - name: Grant execute permission for API gradlew
        run: chmod +x gradlew
        working-directory: services/api

      - name: Build API
        run: ./gradlew clean build
        working-directory: services/api

      # =========================
      # ✅ Batch
      # =========================
      - name: Grant execute permission for Batch gradlew
        run: chmod +x gradlew
        working-directory: services/batch

      - name: Build Batch
        run: ./gradlew clean build
        working-directory: services/batch
